export const C = {
  bg:          '#FAF7F2',
  surface:     '#F2EDE4',
  border:      '#E2D9CC',
  text:        '#2C1F0E',
  muted:       '#8A7A6A',
  light:       '#B8A898',
  accent:      '#8B6B47',
  accentLight: '#F5EDE3',
  sage:        '#6B8F71',
  sageLt:      '#D4E6D6',
  amber:       '#C4883A',
  amberLt:     '#F5E6CC',
  danger:      '#B85450',
  dangerLt:    '#F0DDDB',
  purple:      '#7F77DD',
  purpleLt:    '#EEEDFE',
  purpleMid:   '#534AB7',
  blue:        '#378ADD',
  blueLt:      '#E6F1FB',
  circles:     '#5A7AB8',
  circlesLt:   '#EDF1FA',
  white:       '#FFFFFF',
};
